### ISSUE TITLE
Cannot enable extension (version 1.0.8) on VS Code 1.29

### ISSUE THREAD

**Issue by gmarcan** [hpcc-systems/vscode-ecl#129]
I allowed VS code to update to version 1.29, but now I am unable to use the latest extension (1.0.8). Every time I try to reload and enable - it reloads with the extension disabled.

I am able to load the old extension "ECL" and continue working, but there must be an aspect of the 1.0.8 which causes the IDE to disable the extension.

This was a direct result of updating the IDE. 

Please can someone look into this issue.

Thank you.

**Comment by GordonSmith** [comment]
This is the second report I have seen of this issue - what OS are you running on?

Apparently you can work around it by doing a complete uninstall / reinstall of the extension (rather than simply trying to reload it).  Can you report back if the above works / doesn't work.

(I am investigating it now).

**Comment by GordonSmith** [comment]
Resolved by:  
* https://github.com/hpcc-systems/vscode-ecl/pull/132
* https://github.com/hpcc-systems/vscode-ecl/pull/131
