### ISSUE TITLE
Error when submitting jobs on Mac OSX

### ISSUE THREAD

**Issue by iMikePayne** [hpcc-systems/vscode-ecl#152]
We are getting this error whenever we try to submit a workunit. No matter what cluster used.

`Fetch build version.
Locating Client Tools.
Client Tools: /opt/HPCCSystems/6.4.8/clienttools/bin/eclcc
Generating archive.
Launch failed - Error: ECL Syntax Error(s):  2081: Import names unknown module "lib_fileservices"  2167: Unknown identifier "lib_fileservices"  2167: Unknown identifier "lib_fileservices"  2167: Unknown identifier "lib_fileservices"  2167: Unknown identifier "lib_fileservices"  3001: Too many errors (max = 5); Aborting...`

**Comment by GordonSmith** [comment]
This is very likely related to the version of client tools you have installed (v6.4.8) - is it still appropriate for the servers your targeting?

**Comment by iMikePayne** [comment]
Yes it is. Our cluster's are 6.4.8-1 and update not viable until Jan 2020.

**Comment by GordonSmith** [comment]
Ok - then it might be the case that your ECL is referencing fileservices / std lib from a newer installation, which is not present in v6.4.8?

**Comment by GordonSmith** [comment]
(Just noticing your comment about Mac and I have a feeling that there might have been a known issue with the client tools install for some Mac versions...)

Note: Installing newer client tools (on your client machine) than your target environment (especially point releases) is normally 99.9% safe.  This is because the client tools are simply gathering the referenced ECL code and bundling them into a single XML file (the Archive) and this is what gets submitted to the server for compilation.

**Comment by GordonSmith** [comment]
See:
* https://track.hpccsystems.com/browse/HPCC-19465?jql=text%20~%20%22lib_fileservices%20mac%22
* https://track.hpccsystems.com/browse/HPCC-18683

**Comment by richardkchapman** [comment]
FileServices plugin relies on the fileservices dll exporting the ECL definition (rather than using a separate .ecllib file as some newer plugins do), and as such you'll get errors suh as the one you mention if the dll cannot be loaded for some reason.

Assuming that the fileservices dll is present in the correct location, running eclcc -v may provide some clue as to why the fileservices plugin does not load.

Copying @dcamper as I seem to recall him battling some similar issues at one point.

If all else fails, the ecl definition can be extracted form the fileservices plugin and placed in a .ecllib file manually.
