### ISSUE TITLE
F7 Syntaxcheck fails after version 1.9.5

### ISSUE THREAD

**Issue by oscarfoley** [hpcc-systems/vscode-ecl#207]
Error is "command 'ecl.checkSyntax' not found"
![image](https://user-images.githubusercontent.com/7723954/94119879-5f1b9e00-fe47-11ea-9f7f-91799583871f.png)

I have been updated automatically to version 2.2.4 of this plugin.
If I install old version 1.9.5 F7 syntaxcheck works... but it starts to fail with 2.1.0.

**Comment by GordonSmith** [comment]
ECL Extension v2.x is very dependent on launch configurations - in this case it was failing because there was none.

I will add some improved errors / warnings to catch this scenario and folks who may be submitting via manual "tasks" should consider using launch configurations and the built in Submit command.

**Comment by GordonSmith** [comment]
v2.3.0 includes better error/warning handling.
